# Generated by Django 3.2.9 on 2021-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0003_auto_20211206_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
