# Generated by Django 3.2.9 on 2021-12-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0008_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo1', models.TextField(blank=True, max_length=200, null=True)),
                ('demo2', models.TextField(blank=True, max_length=200, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='postsApp.test')),
            ],
        ),
    ]
