# Generated by Django 3.2.9 on 2021-12-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0009_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1', models.ImageField(blank=True, null=True, upload_to='media/test')),
                ('sample2', models.FileField(blank=True, null=True, upload_to='media/test')),
                ('sample3', models.FilePathField(blank=True, null=True)),
            ],
        ),
    ]
