# Generated by Django 3.2.9 on 2021-12-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0010_imagetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetest',
            name='sample3',
        ),
    ]
